from .command_AreaOfTheTriangle import AreaOfTheTriangle
from .command_botName import BotName
from .command_CoordinatesOfTheCenterOfTheCircle import CoordinatesOfTheCenterOfTheCircle
from .command_dayToNewYear import DayToNewYear
from .command_DistanceFromAPointToAStraightLineInSpace import DistanceFromAPointToAStraightLineInSpace
from .command_FibonacciNumber import FibonacciNumber
from .command_FindTheCoordinatesOfAPoint import FindTheCoordinatesOfAPoint
from .command_QuadraticEquation import QuadraticEquation
from .command_ScalarProductOfVectors import ScalarProductOfVectors
from .command_StefanBoltzmannLaw import StefanBoltzmannLaw
from .command_time import TimeCommand

from .base_abstruct_command import AbstructCommand